[package]
name = "sol-climber"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_rapier3d = { version = "0.28", features = ["parallel", "simd-nightly"] }
# solana-client = "2.2.7"
# solana-sdk = "2.2.2"
